# Generated by Django 3.2.9 on 2021-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='modelNumber',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
