# Generated by Django 3.2.9 on 2021-12-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_tool_modelnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='modelNumber',
            field=models.CharField(max_length=50),
        ),
    ]
