# Generated by Django 3.2.9 on 2021-12-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_tool_modelnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='modelNumber',
        ),
    ]
