# Generated by Django 3.2.9 on 2021-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_tool_modelnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='modelNum',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
