# Generated by Django 3.2.9 on 2021-12-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_modelnum_tool_modelnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='modelNumber',
        ),
    ]
