# Generated by Django 3.2.9 on 2021-12-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_tool_modelnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='modelNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
