# Generated by Django 3.2.9 on 2021-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_tool_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
